import AiTeamPage from "@/app/components/AiTeamPage/AiTeamPage";
import React from "react";

export const metadata = {
  title: "AI Teams - X-TWO-AI",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <AiTeamPage />
    </>
  );
};

export default page;
