import React from "react";
import RecentPage from "../components/RecentPage/RecentPage";

export const metadata = {
  title: "Recent - X-TWO-AI",
  description: "Generated by create next app",
};

const Recent = () => {
  return (
    <>
      <RecentPage />
    </>
  );
};

export default Recent;
