import React from "react";
import SearchPage from "../components/SearchPage/SearchPage";

export const metadata = {
  title: "Search - X-TWO-AI",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <SearchPage />
    </>
  );
};

export default page;
