import StarredPage from "@/app/components/StarredPage/StarredPage";

export const metadata = {
  title: "Starred - X-TWO-AI",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <StarredPage />
    </>
  );
};

export default page;
