import React from "react";
import UpgradePage from "../components/UpgradePage/UpgradePage";

export const metadata = {
  title: "Upgrade - X-TWO-AI",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <UpgradePage />
    </>
  );
};

export default page;
