import Sidebar from "./components/Sidebar/Sidebar";
import "./globals.css";

export const metadata = {
  title: "X-TWO-AI",
  description: "Generated by create next app",
  // Add the external font link here
  links: [
    {
      rel: "stylesheet",
      href: "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-full w-full">
          <div className="sticky top-0 hidden h-full w-full max-w-[300px] lg:block">
            <Sidebar />
          </div>
          <div className="h-full w-full p-2">
            <div className="h-full w-full rounded-xl border bg-white">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
