import localFont from "next/font/local";
import "./globals.css";
import LeftSidebar from "./components/LeftSidebar/LeftSidebar";
import RightSidebar from "./components/RightSidebar/RightSidebar";
import MainContent from "./components/MainContent/MainContent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative flex h-screen">
          <LeftSidebar />
          <div className="overflow-hidden relative w-full">
            <div className="w-full h-full overflow-y-auto custom-scrollbar">
              <MainContent />
              {children}
            </div>
          </div>
          <RightSidebar />
        </div>
      </body>
    </html>
  );
}
