import React from "react";
import HomePage from "./components/HomePage/HomePage";

export const metadata = {
  title: "X-TWO-AI",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <HomePage />
    </>
  );
}
