"use client";
import { FaRobot } from "react-icons/fa";
import { FiShare2 } from "react-icons/fi";
import { LiaFileImportSolid } from "react-icons/lia";
import { TbLayoutList } from "react-icons/tb";
import { HiOutlineViewBoards } from "react-icons/hi";
import { CiFilter } from "react-icons/ci";
import ProjectContent from "./components/ProjectContent/ProjectContent";
import { IoMenu } from "react-icons/io5";
import { useState } from "react";
import ResponsiveSidebar from "./components/Sidebar/ResponsiveSidebar/ResponsiveSidebar";

// export const metadata = {
//   title: "X-TWO-AI",
//   description: "Generated by create next app",
// };
export default function Home() {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const handleOpenSidebar = () => {
    setIsSidebarOpen(true);
  };

  const handleCloseSidebar = () => {
    setIsSidebarOpen(false);
  };

  return (
    <>
      <div className="flex min-h-screen w-full flex-col">
        <div className="sticky top-0 z-20 flex h-12 w-full items-center gap-3 rounded-t-xl border-b bg-white px-8">
          <div
            onClick={handleOpenSidebar}
            className="flex h-7 w-7 cursor-pointer items-center justify-center rounded-md hover:bg-customBlackTransparent"
          >
            <IoMenu className="text-xl" />
          </div>
          <h1 className="text-base font-semibold text-gray-900">Get started</h1>
        </div>
        <div className="mt-6 px-4">
          <button
            className="flex h-8 cursor-pointer flex-row items-center rounded-md bg-gray-100 px-3 text-sm text-gray-600 hover:bg-gray-200 hover:text-gray-700"
            type="button"
          >
            <CiFilter className="text-xl" />
            <span>Filter</span>
          </button>
        </div>
        <div className="pb-15 mb-5 mt-3 px-4">
          <div className="custom-scrollbar mr-5 flex w-full justify-between gap-x-2 overflow-x-auto whitespace-nowrap">
            <div className="group flex w-full cursor-pointer items-center gap-x-3 rounded-md border border-gray-300 px-4 py-4 duration-1000 ease-in-out hover:bg-gray-50">
              <FaRobot className="Linear text-xl duration-1000 ease-in-out" />
              <p className="text-base font-medium">Create with AI</p>
            </div>
            <div className="group flex w-full cursor-pointer items-center gap-x-3 rounded-md border border-gray-300 px-4 py-4 duration-1000 ease-in-out hover:bg-gray-50">
              <TbLayoutList className="text-xl duration-1000 ease-in-out" />
              <p className="text-base font-medium">New List</p>
            </div>
            <div className="group flex w-full cursor-pointer items-center gap-x-3 rounded-md border border-gray-300 px-4 py-4 duration-1000 ease-in-out hover:bg-gray-50">
              <HiOutlineViewBoards className="text-xl duration-1000 ease-in-out" />
              <p className="text-base font-medium">New Board</p>
            </div>
            <div className="group flex w-full cursor-pointer items-center gap-x-3 rounded-md border border-gray-300 px-4 py-4 duration-1000 ease-in-out hover:bg-gray-50">
              <FiShare2 className="text-xl duration-1000 ease-in-out" />
              <p className="text-base font-medium">New Mind Map</p>
            </div>
            <div className="group flex w-full cursor-pointer items-center gap-x-3 rounded-md border border-gray-300 px-4 py-4 duration-1000 ease-in-out hover:bg-gray-50">
              <LiaFileImportSolid className="text-xl duration-1000 ease-in-out" />
              <p className="item-title text-base font-medium">Import</p>
            </div>
          </div>
        </div>
        <ProjectContent />
      </div>
      {isSidebarOpen && (
        <ResponsiveSidebar
          isOpen={isSidebarOpen}
          onClose={handleCloseSidebar}
        />
      )}{" "}
    </>
  );
}
