import MainContent from "./components/MainContent/MainContent";

export const metadata = {
  title: "X-TWO-AI",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <MainContent />
    </>
  );
}
