import React from "react";
import AgeantsPage from "../components/AgentsPage/AgeantsPage";

export const metadata = {
  title: "AI Agents - X-TWO-AI",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <AgeantsPage />
    </>
  );
};

export default page;
