import React from "react";
import CalenderPage from "../components/CalenderPage/CalenderPage";
import CalendarComponent from "../components/CalenderPage/CalendarComponent";

export const metadata = {
  title: "Calender - X-TWO-AI",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <div className="h-full">
        <CalenderPage />
        <CalendarComponent />
      </div>
    </>
  );
};

export default page;
