import React from "react";
import { RiHomeLine, RiMenuUnfold3Line2 } from "react-icons/ri";
import { HiOutlineUsers } from "react-icons/hi";
import ShareSkelton from "../components/Icons/Skeltons/ShareSkelton";

export const metadata = {
  title: "Shared - X-TWO-AI",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <div className="flex h-full w-full">
        <div className="duration-250 hidden w-[260px] shrink-0 flex-col border-r border-gray-200 transition-all duration-300 ease-in-out lg:flex">
          <div className="h-full overflow-y-auto p-3">
            <h3 className="mb-1 flex h-8 w-full cursor-pointer items-center gap-3 rounded-lg px-3 text-base duration-200 ease-in-out hover:bg-gray-100">
              <RiHomeLine className="text-left" />
              Projects
            </h3>
          </div>
        </div>

        <div className="flex h-full w-full flex-col justify-center">
          <div className="flex h-12 shrink-0 items-center px-4 pr-3 text-sm">
            <button className="mr-1 block md:hidden">
              <RiMenuUnfold3Line2 className="text-2xl" />
            </button>
            <div className="flex items-center gap-2 gap-y-2">
              <HiOutlineUsers className="text-xl" />
              Shared with me
            </div>
          </div>
          <div className="flex h-full w-full flex-col items-center justify-center overflow-y-auto px-4 py-3 pt-0 text-center">
            <div className="flex h-full flex-col items-center justify-center text-center">
              <div className="mb-6">
                <ShareSkelton />
              </div>
              <h4 className="mb-2 text-lg font-medium">
                There are no shared projects
              </h4>
              <p className="mb-4 text-center text-base text-gray-500">
                Projects where you have project-only access are displayed here.
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default page;
