import React from "react";
import SharedPage from "../components/SharedPage/SharedPage";

export const metadata = {
  title: "Shared - X-TWO-AI",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <SharedPage />
    </>
  );
};

export default page;
