import React from "react";
import SettingPage from "../components/SettingPage/SettingPage";

export const metadata = {
  title: "Setting - X-TWO-AI",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <SettingPage />
    </>
  );
};

export default page;
