import SettingSidebar from "@/app/components/SettingSidebar/SettingSidebar";
import "../../globals.css";

export const metadata = {
  title: "X-TWO-AI",
  description: "Generated by create next app",
  links: [
    {
      rel: "stylesheet",
      href: "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <div className="flex h-full w-full">
      {/* Sidebar */}
      <div className="hidden h-full w-full max-w-64 border-r lg:block">
        <SettingSidebar />
      </div>

      {/* Main content with a scrollable area and custom scrollbar */}
      <div className="flex h-full shrink-0 flex-col gap-2 px-8 py-5">
        {children}
      </div>
    </div>
  );
}
